/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tom.kafka.examples.account.service;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        AccountService classUnderTest = new AccountService();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
