/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tom.kafka.examples.services;

import com.tom.kafka.examples.KafkaUtils;
import com.tom.kafka.examples.model.AccountEvent;
import com.tom.kafka.examples.model.StockEvent;
import lombok.extern.slf4j.Slf4j;
import org.apache.kafka.common.serialization.Serdes;
import org.apache.kafka.streams.StreamsBuilder;
import org.apache.kafka.streams.Topology;
import org.apache.kafka.streams.kstream.*;

import java.time.Duration;

@Slf4j
public class StockCompensation extends AbstractKafkaApp {

    protected Topology addTopology() {
        StreamsBuilder builder = new StreamsBuilder();

        KStream<String, StockEvent> stockStream = builder.stream("processed-stock-transactions", Consumed.with(KafkaUtils.keySerde,
                KafkaUtils.getSerde(StockEvent.class)));

        KStream<String, AccountEvent> accountStream = builder.stream("processed-account-transactions", Consumed.with(KafkaUtils.keySerde,
                KafkaUtils.getSerde(AccountEvent.class)));

        KStream<String, StockEvent> accountAndStockJoined = stockStream.join(accountStream,
                (stockEvent, accountEvent) -> {
                    log.info("Evaluating stock {} and account {} events for compensation", stockEvent, accountEvent);
                    if (stockEvent.getStatus() == StockEvent.Status.FULFILLED && accountEvent.getStatus() == AccountEvent.Status.REJECTED) {
                        log.info("Created stock compensation for stock event {} and transaction {}", stockEvent.getId(), stockEvent.getTransactionId());
                        stockEvent.setStatus(StockEvent.Status.COMPENSATION);
                    }
                    return stockEvent;
                },
                JoinWindows.of(Duration.ofMinutes(5)),
                StreamJoined.with(
                        Serdes.String(), /* key */
                        KafkaUtils.getSerde(StockEvent.class),   /* left value */
                        KafkaUtils.getSerde(AccountEvent.class))  /* right value */
        );

        accountAndStockJoined.filter((key, value) -> value.getStatus() == StockEvent.Status.COMPENSATION).selectKey((key, accountEvent) -> accountEvent.getStock())
                .to("stock-transactions", Produced.with(KafkaUtils.keySerde, KafkaUtils.getSerde(StockEvent.class)));
        return builder.build();
    }

    public static void main(String[] args) {
        StockCompensation app = new StockCompensation();
        app.run();
    }
}
